LIBPATH =../../../bluespecpcie/
ROOT=../../../
BOARD=vc707
BUILDTOOLS=$(LIBPATH)/buildtools/
TCLARGS=../../../../../bluespecpcie/

CUSTOMBSV= -p +:$(LIBPATH)/dram/src/:$(ROOT)/src/hwlib/:$(ROOT)/flash/src/common/:$(ROOT)/flash/src/model_virtex/:$(ROOT)/flash/src/hw_virtex/:$(ROOT)/flash/virtex/src/
CUSTOMCPP_BSIM=

include $(BUILDTOOLS)/Makefile.base


